source 'https://rubygems.org'

ruby '>= 2.5.0'

group :test do
  gem 'minitest', '~> 5.16'
  gem 'minitest-reporters', '~> 1.5'
  gem 'simplecov', '~> 0.21', require: false
end

group :development do
  gem 'rake', '~> 13.0'
end